<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8db4be02-5ee7-46ce-aa9f-b2ff94912b65}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Test	:	BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF GVL.MainPanel.StopPressed THEN
	
	GVL.MainPanel.StopLightOn();
	GVL.MainPanel.StartLightOff();

ELSIF GVL.MainPanel.StartPressed AND GVL.MainPanel.StopReleased THEN

	GVL.MainPanel.StopLightOff();
	GVL.MainPanel.StartLightOn();	

END_IF]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="25" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="30" Count="1" />
      <LineId Id="35" Count="0" />
      <LineId Id="27" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>